// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Mig15_add_status_about : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig15_add_status_about));
        
        string IMigrationMetadata.Id
        {
            get { return "202106211319234_Mig15_add_status_about"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
