// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Mig16_add_is_Read : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig16_add_is_Read));
        
        string IMigrationMetadata.Id
        {
            get { return "202106211911170_Mig16_add_is_Read"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
